modLoader="javafml" #mandatory
loaderVersion="[36,)" #mandatory This is typically bumped every Minecraft version by Forge. See our download page for lists of versions.
license="MIT"
#issueTrackerURL="https://github.com/Matyrobbrt/UltimateResourceGenerators/issues" #optional
[[mods]] #mandatory
modId="extranetherite" #mandatory
version="${version}" #mandatory
displayName="ExtraNetherite" #mandatory
#updateJSONURL="https://raw.githubusercontent.com/Matyrobbrt/MatyLib/1.16.5/versions_forge_system.json" #optional
#displayURL="https://www.curseforge.com/minecraft/mc-mods/matylib" #optional
#logoFile="examplemod.png" #optional
#credits="Thanks for this example mod goes to Java" #optional
authors="Matyrobbrt" #optional
description='''

'''
[[dependencies.extranetherite]]
    modId="forge" #mandatory
    mandatory=true #mandatory
    versionRange="[36,)" #mandatory
    ordering="NONE"
    side="BOTH"
[[dependencies.extranetherite]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.5,1.17)"
    ordering="NONE"
    side="BOTH"
[[dependencies.extranetherite]]
    modId="matylib"
    mandatory=true
    versionRange="${matylib_version_range}"
    ordering="NONE"
    side="BOTH"

